# version: '3.9'
services:
  pythonapp:
    container_name: python_app
    image: python_app
    ports:
      - "8000:8000"
    networks:
     - python_app
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.3-bookworm
    ports:
      - "5432:5432"
    networks:
      - python_app
      - db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    networks:
      - db
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on: 
      - db

networks:
  python_app:
  db:

volumes:
  pgdata: {}